// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWIYIu6sNIaqBq5pnwLYJXn8n7PVv7PI',
    appId: '1:1086957151994:web:fa49f14cbe96f3976bcb43',
    messagingSenderId: '1086957151994',
    projectId: 'ecommerceapp-42814',
    authDomain: 'ecommerceapp-42814.firebaseapp.com',
    storageBucket: 'ecommerceapp-42814.firebasestorage.app',
    measurementId: 'G-V7F2TZ1H6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRbzkaLoW_AJzYaEx9ABWp8-38FHnjhyM',
    appId: '1:1086957151994:android:8abe2c75a2523cea6bcb43',
    messagingSenderId: '1086957151994',
    projectId: 'ecommerceapp-42814',
    storageBucket: 'ecommerceapp-42814.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-9wg92fQbCzXzMs3zamC8z7G8mcQVQM',
    appId: '1:1086957151994:ios:a02db488812c09f86bcb43',
    messagingSenderId: '1086957151994',
    projectId: 'ecommerceapp-42814',
    storageBucket: 'ecommerceapp-42814.firebasestorage.app',
    androidClientId: '1086957151994-kgj9ddr49aebosq2e3d5o82m6ed7h6t9.apps.googleusercontent.com',
    iosClientId: '1086957151994-bsfnqnph0tne82mhov2dvntn7f3ct1tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}